---
- name: Installing NGINX
  apt:
     name: nginx
     state: latest

- name: Hosting Webpage
  template:
          src: index.html.j2
          dest: /var/www/html/index.html

- name:
  service:
          name: nginx
          state: restarted
